### ISSUE TITLE
changes to work under openbsd 7.0

### ISSUE THREAD

**Issue by jumapico** [adrienverge/openfortivpn#975]
Hi.

Here some suggestions to make openfortivpn run under openbsd.

OS: OpenBSD 7.0
openfortivpn: 1.17.2

To build:

```
$ doas pkg_add autoconf%2.71 automake%1.16
$ cd /path/to/openfortivpn-1.17.2
$ export AUTOCONF_VERSION=2.71
$ export AUTOMAKE_VERSION=1.16
$ ./autogen.sh
$ ./configure --prefix=/usr/local --sysconfdir=/etc
$ make
$ doas make install
```

Note: my config file only uses the options `host`, `port`, `username` and
`password`.

## 1. Option `logfd` not available under `pppd` in openbsd

```diff
Index: openfortivpn-1.17.2/src/tunnel.c
===================================================================
--- openfortivpn-1.17.2.orig/src/tunnel.c
+++ openfortivpn-1.17.2/src/tunnel.c
@@ -277,14 +277,14 @@ static int pppd_run(struct tunnel *tunne
 			 * pppd defaults to logging to fd=1, clobbering the
 			 * actual PPP data
 			 */
-			if (ofv_append_varr(&pppd_args, "logfd")) {
-				free(pppd_args.data);
-				return 1;
-			}
-			if (ofv_append_varr(&pppd_args, "2")) {
-				free(pppd_args.data);
-				return 1;
-			}
+			//      if (ofv_append_varr(&pppd_args, "logfd")) {
+			//      	free(pppd_args.data);
+			//      	return 1;
+			//      }
+			//      if (ofv_append_varr(&pppd_args, "2")) {
+			//      	free(pppd_args.data);
+			//      	return 1;
+			//      }
 		}
 		if (tunnel->config->pppd_plugin) {
 			if (ofv_append_varr(&pppd_args, "plugin")) {
```

without this we get the error:

```
$ doas /usr/local/bin/openfortivpn -vv
...
DEBUG:  ssl_read thread
pppd: unrecognized option 'logfd'
pppd version 2.3 patch level 5
Usage: pppd [ options ], where options are:
        <device>        Communicate over the named device
        <speed>         Set the baud rate to <speed>
        <loc>:<rem>     Set the local and/or remote interface IP
                        addresses.  Either one may be omitted.
        asyncmap <n>    Set the desired async map to hex <n>
        auth            Require authentication from peer
        connect <p>     Invoke shell command <p> to set up the serial line
        crtscts         Use hardware RTS/CTS flow control
        defaultroute    Add default route through interface
        file <f>        Take options from file <f>
        modem           Use modem control lines
        modem_chat      Use modem control lines during chat
        mru <n>         Set MRU value to <n> for negotiation
        netmask <n>     Set interface netmask to <n>
See pppd(8) for more options.
WARN:   read returned 0
```

## 2. Option `receive-all` not available under `pppd` in openbsd

```diff
Index: openfortivpn-1.17.2/src/tunnel.c
===================================================================
--- openfortivpn-1.17.2.orig/src/tunnel.c
+++ openfortivpn-1.17.2/src/tunnel.c
@@ -242,7 +242,7 @@ static int pppd_run(struct tunnel *tunne
 				"noauth",
 				"default-asyncmap",
 				"nopcomp",
-				"receive-all",
+				// "receive-all", // not available in openbsd
 				"nodefaultroute",
 				"nodetach",
 				"lcp-max-configure", "40",
```

without this we get the error:

```
$ doas /usr/local/bin/openfortivpn -vv
...
DEBUG:  if_config thread
pppd: unrecognized option 'receive-all'
pppd version 2.3 patch level 5
Usage: pppd [ options ], where options are:
        <device>        Communicate over the named device
        <speed>         Set the baud rate to <speed>
        <loc>:<rem>     Set the local and/or remote interface IP
                        addresses.  Either one may be omitted.
        asyncmap <n>    Set the desired async map to hex <n>
        auth            Require authentication from peer
        connect <p>     Invoke shell command <p> to set up the serial line
        crtscts         Use hardware RTS/CTS flow control
        defaultroute    Add default route through interface
        file <f>        Take options from file <f>
        modem           Use modem control lines
        modem_chat      Use modem control lines during chat
        mru <n>         Set MRU value to <n> for negotiation
        netmask <n>     Set interface netmask to <n>
See pppd(8) for more options.
WARN:   read returned 0
```

A workaround with the current code can be the usage of the `--pppd-call` option
and not using the option `receive-all` in the script.  Example:

```
$ cat /etc/ppp/peers/openfortivpn
230400          # speed
:169.254.2.1    # <local_IP_address>:<remote_IP_address>
noipdefault
noaccomp
noauth
default-asyncmap
nopcomp
nodefaultroute
nodetach
lcp-max-configure 40
mru 1354
debug
$ doas /usr/local/bin/openfortivpn -vv --pppd-call=openfortivpn
```

## 3. Differences in `/sbin/route` command in openbsd

The syntax of the `route` command in openbsd is different from the expected.

Example:

```
$ doas /usr/local/bin/openfortivpn -vv
...
DEBUG:  Setting route to vpn server...
DEBUG:  ip route show to 190.64.5.10/255.255.255.255 via 192.168.1.1 dev -
DEBUG:  /sbin/route -n add -host 190.64.5.10 192.168.1.1
add host 190.64.5.10: gateway 192.168.1.1: File exists
DEBUG:  /sbin/route -n add -net 172.17.1.8 -netmask 255.255.255.255 -interface ppp0
route: ppp0: bad address
DEBUG:  /sbin/route -n add -net 10.209.0.29 -netmask 255.255.255.255 -interface ppp0
route: ppp0: bad address
...
```

After some tries, changing

```
/sbin/route -n add -net 10.209.0.29 -netmask 255.255.255.255 -interface ppp0
```

to

```
/sbin/route -n add -net 10.189.0.0 -netmask 255.255.254.0 172.17.189.140
```

works.

*Note*: the ip `172.17.189.140` is the hardcoded ip used with `pppd`.

Example of a patch for this case:

```diff
Index: openfortivpn-1.17.2/src/ipv4.c
===================================================================
--- openfortivpn-1.17.2.orig/src/ipv4.c
+++ openfortivpn-1.17.2/src/ipv4.c
@@ -644,9 +644,10 @@ static int ipv4_set_route(struct rtentry
                strcat(cmd, " ");
                strncat(cmd, inet_ntoa(route_gtw(route)), 15);
        } else {
-               strcat(cmd, " -interface ");
-               strncat(cmd, route_iface(route),
-                       SHOW_ROUTE_BUFFER_SIZE - strlen(cmd) - 1);
+               //      strcat(cmd, " -interface ");
+               //      strncat(cmd, route_iface(route),
+               //              SHOW_ROUTE_BUFFER_SIZE - strlen(cmd) - 1);
+               strcat(cmd, " 172.17.189.140");
        }

        log_debug("%s\n", cmd);
```

Maybe using as workaround the suggestion given in the wiki,
[How to add specific routes using pppd](https://github.com/adrienverge/openfortivpn/wiki#how-to-add-specific-routes-using-pppd),
works.

**Obviously, the previous diffs are only to highlight the relevant code and not
a proposition about the changes.**

I can help providing patches if someone can guide me in the desired form to
adapt the code for run under openbsd.

**Comment by DimitriPapadopoulos** [comment]
I think openfportivpn works under FreeBSD using `ppp` instead of `pppd`. Perhaps you should get OpenBSD to use `ppp` instead of `pppd` if both are available.

**Comment by jumapico** [comment]
Hi @DimitriPapadopoulos

`ppp` [isn't available](https://man.openbsd.org/?query=ppp&apropos=1&sec=0&arch=default&manpath=OpenBSD-current) in the OpenBSD base system nor as a ports package with a name that contains `ppp` or `point`.

As you stated, for FreeBSD [I can confirm](https://www.freebsd.org/cgi/man.cgi?query=ppp&sektion=8&apropos=0&manpath=FreeBSD+13.0-RELEASE+and+Ports) that the `ppp` command exists.

**Comment by DimitriPapadopoulos** [comment]
Ideally, we should abandon `pppd`/`ppp` and use an embedded PPP implementation and a `tun` device instead. That would be more portable and robust. Unfortunately, that's more work :disappointed:

**Comment by DimitriPapadopoulos** [comment]
You could try the [tun](https://github.com/adrienverge/openfortivpn/tree/tun) branch which gets rid of `ppp`/`pppd` and uses embedded PPP code instead.

This branch works for me. You'll see a few error messages here and there, but it works on Linux and appears to be stable.

**Comment by jumapico** [comment]
Hi @DimitriPapadopoulos !
Thanks for your update on this matter.
Sadly, it doesn't work in openbsd 7.2 (-current):

```
$ git clone git@github.com:adrienverge/openfortivpn.git
$ git checkout tun
$ export AUTOCONF_VERSION=2.71
$ export AUTOMAKE_VERSION=1.16
$ ./autogen.sh
...
$ ./configure
...
checking for libsystemd... no
libsystemd not present
...
checking for net/route.h... yes
checking for libutil.h... no
checking for linux/if_ppp.h... no
checking for linux/if_tun.h... no
checking for mach/mach.h... no
checking for pty.h... no
checking for semaphore.h... yes
...
checking for write... yes
checking for pthread_mutexattr_setrobust... no
checking whether rtentry is available and has rt_dst... no
checking for /proc/net/route... no
checking for /usr/sbin/netstat... no
checking for /usr/bin/netstat... yes
configure: HAVE_PROC_NET_ROUTE... 0
configure: NETSTAT_PATH... /usr/bin/netstat
checking for resolvconf... DISABLED
configure: RESOLVCONF_PATH... DISABLED
configure: HAVE_RESOLVCONF... 0
configure: USE_RESOLVCONF... 0
configure: HAVE_SO_BINDTODEVICE... 0
checking that generated files are newer than configure... done
...
$ gmake
...
  CC       src/openfortivpn-config.o
  CC       src/openfortivpn-hdlc.o
  CC       src/openfortivpn-http.o
  CC       src/openfortivpn-io.o
src/io.c:390:22: error: use of undeclared identifier 'PPP_LCP'
                        *ppp_type = htons(PPP_LCP);
                                          ^
src/io.c:390:22: error: use of undeclared identifier 'PPP_LCP'
src/io.c:390:22: error: use of undeclared identifier 'PPP_LCP'
src/io.c:390:22: error: use of undeclared identifier 'PPP_LCP'
src/io.c:463:10: error: use of undeclared identifier 'PPP_CHAP'
                                case PPP_CHAP: {
                                     ^
src/io.c:467:20: warning: extension used [-Wlanguage-extension-token]
                                        } *payload = (typeof(*payload) *)co_data(co);
                                                      ^
src/io.c:749:8: warning: implicit declaration of function 'ioctl' is invalid in C99 [-Wimplicit-function-declaration]
        ret = ioctl(sd, SIOCADDRT, &rt);
              ^
src/io.c:749:18: error: use of undeclared identifier 'SIOCADDRT'
        ret = ioctl(sd, SIOCADDRT, &rt);
                        ^
src/io.c:776:22: error: use of undeclared identifier 'PPP_IPCP'
                        *ppp_type = htons(PPP_IPCP);
                                          ^
src/io.c:776:22: error: use of undeclared identifier 'PPP_IPCP'
src/io.c:776:22: error: use of undeclared identifier 'PPP_IPCP'
src/io.c:776:22: error: use of undeclared identifier 'PPP_IPCP'
src/io.c:1251:9: error: use of undeclared identifier 'PPP_LCP'
                        case PPP_LCP:
                             ^
src/io.c:1254:9: error: use of undeclared identifier 'PPP_IPCP'
                        case PPP_IPCP:
                             ^
src/io.c:1257:9: error: use of undeclared identifier 'PPP_IP'
                        case PPP_IP:
                             ^
src/io.c:1258:9: error: use of undeclared identifier 'PPP_IPV6'
                        case PPP_IPV6:
                             ^
2 warnings and 14 errors generated.
gmake: *** [Makefile:572: src/openfortivpn-io.o] Error 1
```

Modifying the file `src/io.c` to remove the messages about undefined identifiers
like `PPP_*` (see:
<https://github.com/openbsd/src/blob/master/sys/net/ppp_defs.h>)

```
$ git diff
diff --git a/src/io.c b/src/io.c
index 916f2d0..df59d3a 100644
--- a/src/io.c
+++ b/src/io.c
@@ -39,6 +39,8 @@
 #include <net/if_ppp.h>
 #endif

+#include <net/ppp_defs.h>
+
 #include <assert.h>
 #include <errno.h>
 #include <signal.h>
$ gmake
  CC       src/openfortivpn-io.o
src/io.c:469:20: warning: extension used [-Wlanguage-extension-token]
                                        } *payload = (typeof(*payload) *)co_data(co);
                                                      ^
src/io.c:751:8: warning: implicit declaration of function 'ioctl' is invalid in C99 [-Wimplicit-function-declaration]
        ret = ioctl(sd, SIOCADDRT, &rt);
              ^
src/io.c:751:18: error: use of undeclared identifier 'SIOCADDRT'
        ret = ioctl(sd, SIOCADDRT, &rt);
                        ^
2 warnings and 1 error generated.
gmake: *** [Makefile:572: src/openfortivpn-io.o] Error 1
```

As far as I know `SIOCADDRT` doesn't exist in openbsd.
(I searched it in
<https://github.com/openbsd/src/blob/master/sys/sys/sockio.h> and using grep in
the source code: `cd /path/to/openbsd/src; grep -r -i SIOCADDRT .`)

From <https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/sockios.h>:

```
#define SIOCADDRT	0x890B		/* add routing table entry	*/
```

From <https://man.openbsd.org/route.4>, maybe an alternative to `SIOCADDRT ioctl` for openbsd is `RTM_ADD/RTM_NEWADDR`?

From above man page:

```
#define RTM_ADD		0x1	/* Add Route */
#define RTM_NEWADDR	0xc	/* address being added to iface */
```

**Comment by DimitriPapadopoulos** [comment]
Indeed, the `PPP_` stuff needs to be made more portable. Header file `<net/ppp_defs.h>` is available in Linux too, perhaps that's the one we should use.

Or better yet, we should probably define PPP_ constants in openfortivpn instead of relying on non-standard  header files such as `<net/if_ppp.h>`.

**Comment by DimitriPapadopoulos** [comment]
About the routing stuff, I really don't know. Setting DNS parameters and modifying routing on POSIX systems relies on undocumented and/or moving programming APIs.

Perhaps we should move DNS and routing stuff to an external script, as suggested in #678. At least, commands for modifying DNS parameters and routing are better documented than programming APIs.

**Comment by DimitriPapadopoulos** [comment]
9e9bdbec66243b2b134ddaee27ee0d9bcb128fa2 should take care of `PPP_` issues.
